### ISSUE TITLE
Potential leak of memory pointed to by 'sf' in sirfilecache.c:401:12 (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#10]
per Clang Analyzer:

![Screenshot 2023-06-24 at 23-51-20 sirfilecache c](https://github.com/aremmell/libsir/assets/61629094/e2f4c25e-361b-41b9-be40-91ac3e9a1754)

**Comment by johnsonjh** [comment]
Resolved in syslog

**Comment by aremmell** [comment]
To be clear–I added the fix that was implied by that tool, and it crashed in Travis CI (double-free). If you look at _sirfile_create, it frees before returning if it fails.
