### ISSUE TITLE
Use compiler-assisted format string verification where possible

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#120]
Since sir takes printf-style strings, some compilers let this fact be annotated, so calls to libsir logging functions will be verified as if they were printf calls, *i.e.* producing helpful warnings on GCC when `-Wformat` is used.

See: https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-format-function-attribute

We could do this like:

```c
#ifdef __GNUC__
# define WFORMAT __attribute__ ((format (printf, 2, 3)))
#else
# define WFORMAT 
#endif
```

... and then put WFORMAT in the magic spots.  We'd extend this for other compatible compilers - they all seem to use something very much like this.  

from the linked docs:
> The parameter archetype determines how the format string is interpreted, and should be printf, scanf, strftime, gnu_printf, gnu_scanf, gnu_strftime or strfmon. (You can also use __printf__, __scanf__, __strftime__ or __strfmon__.) On MinGW targets, ms_printf, ms_scanf, and ms_strftime are also present. archetype values such as printf refer to the formats accepted by the system’s C runtime library, while values prefixed with ‘gnu_’ always refer to the formats accepted by the GNU C Library. On Microsoft Windows targets, values prefixed with ‘ms_’ refer to the formats accepted by the msvcrt.dll library. The parameter string-index specifies which argument is the format string argument (starting from 1), while first-to-check is the number of the first argument to check against the format string. For functions where the arguments are not available to be checked (such as vprintf), specify the third parameter as zero. In this case the compiler only checks the format string for consistency. For strftime formats, the third parameter is required to be zero. Since non-static C++ methods have an implicit this argument, the arguments of such methods should be counted from two, not one, when giving values for string-index and first-to-check. In the example above, the format string (my_format) is the second argument of the function my_print, and the arguments to check start with the third argument, so the correct parameters for the format attribute are 2 and 3.

**Comment by johnsonjh** [comment]
This works in Clang too.

**Comment by johnsonjh** [comment]
I've got it working - it'll need cleanup and I'll try to get it in tomorrow

**Comment by johnsonjh** [comment]
@aremmell I'll clean it up but ...

![IMG_7875](https://github.com/aremmell/libsir/assets/61629094/047e456e-de61-40fa-98ef-e7c84463eb97)

found one already we can fix - `%zu`

**Comment by aremmell** [comment]
Fixing
