### ISSUE TITLE
Doxygen footer

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#124]
I noticed your Doxygen footer does not have the time and date like mine does, which is ... annoying IMO.

I can do `sed --version 2>&1 | grep -qi 'GNU sed' && find docs -name '*.html' -exec sed -i 's/ on .* for libsir by / by /' {} \;` to get rid of it.  That's done that way since `-i` is a GNU extension (and Solaris and BSD have it, but it's not quite compatible).

Is there some setting I'm missing, or should I look at adding something like this to the `make docs` recipe?

**Comment by aremmell** [comment]
It's a Doxyfile setting, iirc. Either that, or the doxygen -g or --generate or whatever it is creates a header, footer, etc. template that you can edit. I could have taken it out on purpose. I don't really care either way if it's there or not.

I'll check Doxyfile. You check if you re-generate them if it creates a timestamp version.

**Comment by aremmell** [comment]
`doxygen -w html new_header.html new_footer.html new_stylesheet.css Doxyfile`

**Comment by aremmell** [comment]
N/M: HTML_TIMESTAMP         = NO

**Comment by aremmell** [comment]
> Weird - I see that setting there but I still get the time stamps added when I run `make docs` ...

Wait, you're trying to make time stamps appear or not appear? If you set HTML_TIMESTAMP = YES it should generate them... if it doesn't, I probably modified the footer html?

**Comment by johnsonjh** [comment]
To not appear.  I run make docs and they do appear.  That's what's weird

**Comment by aremmell** [comment]
Let me see what happens on my end. While I'm thinking about it, you don't need to run advpng on anything under `docs/res` or `docs/sources`. All those files are committed to git and are not generated by Doxygen.

**Comment by aremmell** [comment]
<img width="349" alt="Screenshot 2023-07-13 at 05 42 29" src="https://github.com/aremmell/libsir/assets/812759/b6e1018c-ed52-4105-a3d2-3382c439f5f1">

This is what I get with make docs and HTML_TIMESTAMP = NO...

**Comment by johnsonjh** [comment]
So strange.  Mine still does.  And it's also Doxygen 1.9.7!

**Comment by johnsonjh** [comment]
I'll add my sed magic in, it's fast and a null-op otherwise.

**Comment by aremmell** [comment]
Let's just focus on other stuff? We'll just make sure I gen the docs for now, till we figure out wtf.

**Comment by aremmell** [comment]
What system are you running doxygen on that generates the timestamps? So weird. Search didn't yield much. We must be doing something odd.

**Comment by johnsonjh** [comment]
Fedora 38.  It comes with Doxygen 1.9.6, so I build 1.9.7 (with rpmbuild, from the upstream srpm).  The 1.9.6 package acts the same way though, as does the package in Rawhide.

**Comment by johnsonjh** [comment]
It's not a big deal either way - the main reason I don't like it is because it makes the git commits bigger since it's updating the date in all files.

**Comment by aremmell** [comment]
Yeah, I built 1.9.7 from source using Clang on macOS 13.4. Something is afoot. There's no way that's a bug that nobody else has written about online.

And yeah, that is lame. I would just revert docs/ when you commit and I'll regen when we merge PRs for now, unless you want to try and figure it out.

Does doxygen have a verbose mode? I think you can turn on a log file...

**Comment by johnsonjh** [comment]
I'll try to figure it out later, gotta get some sleep.  Or I'll just do the sed crap myself until I do figure it out.  So we'll close this for now.
