### ISSUE TITLE
Log files created even if `sir_addfile` returns NULL

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#127]
Something about the process of adding a file is opening/creating the file before failure to add occurs, then not undoing that process. Needs fixing.

**Comment by aremmell** [comment]
I can’t reproduce this anymore. It must’ve been something modified transiently and is now resolved. Closing; can re-open if we ever see `should-fail.log` in the file system.

**Comment by aremmell** [comment]
Located a spot in the source where this is possible. `sirfilecache.c:131` returns after opening (creating) the file with a value that will cause the calling function to abort

**Comment by johnsonjh** [comment]
Fixed in master
