### ISSUE TITLE
BUG: `_sir_fcache_pred_path` is easily breakable

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#135]
This function is used to match an incoming log file against existing ones in order to avoid duplicates. It simply `strncmp`s the paths, which isn't good enough.

**Example 1:**
- File 1: `/home/ryan/logs/foo.log`
- File 2: `~/logs/foo.log`

**Example 2:**
- File 1: `C:\Users\ryan\logs\foo.log`
- File 2: `C:\USERS\RYAN\LOGS\FOO.LOG`

**Example 3:**
- File 1: `/home/ryan/logs/foo.log`
- File 2: *(cwd is /home/ryan/)* `./logs/foo.log`

These are the same file, but `strncmp` != 0.

**On Windows**
- [GetFileInformationByHandle](http://msdn.microsoft.com/en-us/library/aa364952(VS.85).aspx) -- compare `dwVolumeSerialNumber, nFileIndexLow, nFileIndexHigh`

**On Linux/macOS/Unix** 
- `realpath`?
- `stat`?

- [x] Windows
- [x] Linux/macOS/Unix

**Comment by johnsonjh** [comment]
readlink and/or realpath would be the way to go, I bet

**Comment by johnsonjh** [comment]
stat for detecting hardlinks

**Comment by aremmell** [comment]
- On Windows: now uses `GetFileInformationByHandle` if both files exist and can be opened. If either cannot be opened, falls back to `GetFullPathName` (essentially `realpath` but for Windows) and `StrCmpI`
- On every other platform: now uses `stat` if both files exist (i.e. `realpath` does not return an error value). If either do not exist/`realpath` fails, falls back to `strncmp` on the canonical paths returned by `realpath`.
