### ISSUE TITLE
Install sirtypes.h and sirplatform.h when doing make install

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#137]
They aren't being installed currently ... 

Subtasks:

- [ ] Reorganize file system: *.c to `src` and *.h to `include`.
- [ ] extern "C" in any header that gets installed and exports functions

**Comment by johnsonjh** [comment]
We actually want: `sirplatform.h sirtypes.h sirimpl.h sirplatform.h sirconfig.h siransimacros.h sir.h`

**Comment by aremmell** [comment]
yeah, those, and maybe `sirfilesystem.h` and `sirhelpers.h` since those both have some pretty useful functionality you would have to rewrite if you didn't have access to it. only me and you will know what that is most likely but i'd like those headers too.

**Comment by johnsonjh** [comment]
Yes - the filesystem stuff is useful and should probably be easily available to the user.

**Comment by johnsonjh** [comment]
Maybe we should do what *libuv* does? They have `uv.h` and then `uv/errno.h`, `uv/linux.h`, `uv/threadpool.h, uv/unix.h`, `uv/version.h`, which is installed to `$PREFIX`:

```sh
.rw-r--r-- root root  66 KB Tue Jul 12 12:16:33 2022 /usr/include/uv.h
.rw-r--r-- root root  19 KB Tue Jul 12 12:16:33 2022 /usr/include/uv/unix.h
.rw-r--r-- root root 1.8 KB Tue Jul 12 12:16:33 2022 /usr/include/uv/version.h
.rw-r--r-- root root 1.7 KB Tue Jul 12 12:16:33 2022 /usr/include/uv/linux.h
.rw-r--r-- root root 1.5 KB Tue Jul 12 12:16:33 2022 /usr/include/uv/threadpool.h
.rw-r--r-- root root  10 KB Tue Jul 12 12:16:33 2022 /usr/include/uv/errno.h
```

So, we could have something similar, like ... `sir.h`, and then `sir/platform.h`, `sir/types.h`, `sir/impl.h`, `sir/config.h`, `sir/ansimacros.h`, `sir/filesystem.h`, `sir/helpers.h`.  

`sir.h` would include `sir/platform.h`, `sir/types.h`, etc.

What do you think?

**Comment by aremmell** [comment]
Seems reasonable to me as long as we don't have to make a sir directory inside the repo and rename the headers (if we can do it in a script at install time)

**Comment by johnsonjh** [comment]
> Seems reasonable to me as long as we don't have to make a sir directory inside the repo and rename the headers (if we can do it in a script at install time)

Hrrm.  I don't know a clean way to do that, unless you don't mind moving stuff to `src/*` and `include/*` directories at the top-level.

**Comment by aremmell** [comment]
> > Seems reasonable to me as long as we don't have to make a sir directory inside the repo and rename the headers (if we can do it in a script at install time)
> 
> Hrrm. I don't know a clean way to do that, unless you don't mind moving stuff to `src/*` and `include/*` directories at the top-level.

Actually, I was just about to suggest that we do precisely that. The file listing is getting unruly, and it's not going to get any better.

**Comment by johnsonjh** [comment]
Done in #160
