### ISSUE TITLE
Makefile dependency problems?

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#142]
If I have everything in such a state that if I do `make` I get "nothing to make," then say change one line in sirinternal.c, save it again, run `make` again, I get a ton of linker errors from functions within libsir.

What do you make of it? Assigning to you because you're the Makefile king compared to me. Want to see if you can repro?

**Comment by johnsonjh** [comment]
I'll try to figure it out ...  sorry, busy Friday...

**Comment by johnsonjh** [comment]
> If I have everything in such a state that if I do `make` I get "nothing to make," then say change one line in sirinternal.c, save it again, run `make` again, I get a ton of linker errors from functions within libsir.
> 
> 
> 
> What do you make of it? Assigning to you because you're the Makefile king compared to me. Want to see if you can repro?

Hrrm, odd.  It should remake just  sirinternal.c if since that changed and go from there.  I'll have to see what's up there.

**Comment by aremmell** [comment]
Holy mother of god that was a nightmare. Visual Studio actually created a bad project file through its GUI wizard. I had to compare it line-by-line to a working one. That just took about 3 hours to get it right... but the code worked on the second try after I fixed a couple obvious oversights

**Comment by johnsonjh** [comment]
@aremmell just getting home and got some things to do before settling in - maybe we should move the release date to Monday so I have the weekend to poke at it ?

**Comment by aremmell** [comment]
Yeah, it's not a hard deadline, but we really should stop adding things now and focus on testing all the stuff that's new... if you could help me test the plugins branch that would be awesome...

I couldn't wait so I did make a ghetto little script to build the dummy plugin, and I added it to the Makefile. Could you do it properly instead of hacked?

We'll need that in order to add tests for loading good and bad plugins, which I've already got mapped out.

I think we should focus on trying to break stuff. Like you probably should re-test everything after I added that include to sirplatform and added -ldl to the LDFLAGS...

I've been at this for like 24+ hours straight so I'm gonna take a nap or at least a rest for a couple hours but I'll be back

You got Telegram or something? This chatting on GitHub is annoying lol

**Comment by johnsonjh** [comment]
Nothing else I need to add for a release other than AIX support.  

I'll be able to handle the make stuff ...

I'll make an issue for adding popular RTOS support (Zephyr, RTEMS, QNX, VxWorks) but it's not at all pressing ... 

You ok with IRC?  How about Slack?  DPS8M uses it already, I can make a separate libsir channel

**Comment by johnsonjh** [comment]
https://join.slack.com/t/multics-os/shared_invite/zt-1ejykw0eu-mHHr0_FS8o4GOeAVXKmQew

**Comment by johnsonjh** [comment]
Fixed in current branches
