### ISSUE TITLE
Use of memory after it is freed in sirfilesystem.c:244:5 (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#17]
per Clang Analyzer:

![Screenshot 2023-06-25 at 00-01-30 sirfilesystem c](https://github.com/aremmell/libsir/assets/61629094/e1aedf9a-44ca-4783-a198-d8278fe673fe)

**Comment by aremmell** [comment]
```c
char* _sir_getappbasename(void) {
    char* filename = _sir_getappfilename();
    if (!_sir_validstr(filename))
        return NULL;
```

**Comment by johnsonjh** [comment]
I'll fix later (not on my phone)

**Comment by johnsonjh** [comment]
Fixed in syslog branch
