### ISSUE TITLE
Portability: Returning an integer in a function with pointer return type is not portable in sirtextstyle.c:32:9 (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#18]
from Cppcheck:

`sirtextstyle.c:32:9: portability: Returning an integer in a function with pointer return type is not portable. [CastIntegerToAddressAtReturn]`
```c
         return false;
         ^
```

**Comment by aremmell** [comment]
Whoops. Refactoring bug. I just changed that from bool to const char*

**Comment by aremmell** [comment]
Fixed in 84462b9b11d16b67038cf2ffc290d7d9c998263b
