### ISSUE TITLE
Suspicious equality comparison in sirhelpers.c:48:16 (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#21]
from Cppcheck:

`sirhelpers.c:48:16: warning: inconclusive: Found suspicious equality comparison. Did you intend to assign a value instead? [constStatement]`
```c
    intptr_t h = = _get_osfhandle(id); /* strange: Windows does it entirely differently. */  
```

(If this one is intentional, I'll suppress.)

**Comment by aremmell** [comment]
Yep, that's a typo I missed (don't test on Windows often).
