### ISSUE TITLE
Capture the program name

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#216]
Most of systems we support have a way to explicitly get the ***program name*** (which can be something different than the default thread name, if thread names are supported).

* OpenBSD has [`getprogname()`](https://man.openbsd.org/getprogname.3)
* Haiku and GNU/Linux with glibc have [`*program_invocation_name`](https://www.gnu.org/software/libc/manual/html_node/Error-Messages.html#index-program_005finvocation_005fname)
* Solaris and illumos have [`getexecname()`](https://docs.oracle.com/cd/E86824_01/html/E54766/getexecname-3c.html)
* Microsoft Windows has [`__argv` (`const char *p = __argv && __argv[0] ? __argv[0] : "?";`)](https://learn.microsoft.com/en-us/cpp/c-runtime-library/argc-argv-wargv?view=msvc-170)
* AIX has [`getprocs()`](https://www.ibm.com/docs/en/aix/7.2?topic=g-getprocs-subroutine)
* QNX (and I *think* FreeBSD/NetBSD/etc. too) have [`*__progname`](http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.neutrino_lib_ref%2Fp%2F__progname.html)
* ... and for pretty much anything else, we can just capture `argv[0]` early, when initializing libsir, and save it to use later.  Most users will initialize libsir early in their main, so this is sane, and,
* as a fallback (or override), allow it to be set to something explicitly.

The ***program name*** should be, by default, a third "field", after the *{PID}* and *{TID/thread name}* fields in the default logs and output (IMO).

The ***program name*** will be constant and static, set once when libsir is initialized.  It won't ever change at runtime, unlike thread names or task/process names (`argv[0]`) which *can* be changed later by the program.

This should be a pretty low effort addition for pretty much everything but AIX.

Comments welcome.

**Comment by aremmell** [comment]
On Windows the official method is `_get_pgmptr` (and `_get_wpgmptr` for wchar_t): https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/get-pgmptr?view=msvc-170

**Comment by johnsonjh** [comment]
I think we can get this for 2.3.0?

**Comment by aremmell** [comment]
Technically we are already doing this, at least for syslog. That's what `_sir_getappfilename` is for actually.

**Comment by johnsonjh** [comment]
The program name is different than the file name though.

For example, the filename is often the program name, but not always.  BSD has __progname (and OpenBSD setprogname and getprogname for example), which is described as:

> These utility functions get and set the current program's name as used by various error-reporting functions. getprogname() returns the name of the current program.  This function is typically useful when generating error messages or other diagnostic output.

There is also setproctitle and getproctitle:

> The setproctitle() function sets the invoking process's title.  The process title is set to the last component of the program name, followed by a colon, a single space, and the formatted string specified by fmt. If fmt is NULL, the colon and formatted string are omitted.  The length of a process title is limited to 2048 bytes.

FreeBSD, DragonFly, and other systems (some embedded OS I worked on, forget which, I remember offhand) have variants of this:

> The setproctitle_fast() variant is optimized for high frequency updates, but may make the ps(1) command slightly slower by not updating the kernel cache of the program arguments. The setproctitle() functions are implicitly non-standard.  Other methods of causing the ps(1) command line to change, including copying over the argv[0] string are also implicitly non-portable.  It is preferable to use an operating system supplied setproctitle() if present.

These are both possibly also different from `argv[0]`, which may or may not be a path, and it might be empty too, because, programs don't have to be launched from files on disk at all, if there even is a filesystem.

Setting a name via proctitle will change what is displayed by tools like `ps`, `top`, etc.  Just setting a program name alone usually does not.

Example:
![IMG_8271](https://github.com/aremmell/libsir/assets/61629094/06d84c81-d1b1-4608-ac57-9d4f3dfc81c8)

Result:
![IMG_8272](https://github.com/aremmell/libsir/assets/61629094/0b8fc697-c85a-4e06-82a6-c8856181464d)

For many scripting languages on various systems, like REXX or Perl, the program name will likely be the name of the script, rather than "rexx" or "perl", and programs can set stuff too to customize. Here's some `ps` output from a Perl-based stats program I use, invoked as "jstatx linear" (but it's called statx normally):

 UID   PID  PPID C PRI NI   VSZ  RSS MWCHAN STAT TT     TIME COMMAND
1002 46505 45184 1  28  0 19548 6428 ttyin  I+    1  0:00.11 statx: linear (perl)

FreeBSD says further:
> The ps utility first tries to obtain the arguments cached by the kernel (if they were shorter than the value of the kern.ps_arg_cache_limit sysctl).  The process can change the arguments shown with setproctitle(3).  Otherwise, ps makes an educated guess as to the file name and arguments given when the process was created by examining memory or the swap area.  The method is inherently somewhat unreliable and in any event a process is entitled to destroy this information.  The ucomm (accounting) keyword can, however, be depended on.  If the arguments are unavailable or do not agree with the ucomm keyword, the value for the ucomm keyword is appended to the arguments in parentheses.

Or here's a classic from my youth, to bother the Sysadmin lol.  This worked in 1989 or so for sure:

```
$ exec env ARGV0="DAVE... you momma so fat you gotta grease the doorframes to get her thru" zsh
$ ps
  PID TT  STAT    TIME COMMAND
46894  2  R+   0:00.00 DAVE... you momma so fat you gotta grease the doorframes to get her thru (ps)
46895  2  R+   0:00.00 DAVE... you momma so fat you gotta grease the doorframes to get her thru --color . (grep)
46896  2  R+   0:00.00 DAVE... you momma so fat you gotta grease the doorframes to get her thru (cat)
```

Dave always hated me.  I had a script to randomize the jokes.

Anyway, just saying we should support this but also be careful with how we implement it since it's non-trivial to do cross-platform nicely.

**Comment by aremmell** [comment]
Makes sense. We can ditch `_sir_getappfilename` too, then. It's a weak link anyway

**Comment by johnsonjh** [comment]
> Makes sense. We can ditch `_sir_getappfilename` too, then. It's a weak link anyway

It's good for different purposes - I'll have document the differences and the use cases for each.

**Comment by johnsonjh** [comment]
Closing for various reasons, but probably better handled in the application which that then sets the name rather than by libsir trying to deduce something from the OS and environment
