### ISSUE TITLE
Function argument names different in sirerrors.h:93:45 and sirerror.c.67:45 (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#23]
from Cppcheck:

`sirerrors.c:67:45: style: inconclusive: Function '__sir_setoserror' argument 2 names different: declaration 'msg' definition 'message'. [funcArgNamesDifferent]`
```c
void __sir_setoserror(int code, const char* message, const char* func,                                                           
                                            ^                          
```

---

1. `sirerrors.h:93:45: note: Function '__sir_setoserror' argument 2 names different: declaration 'msg' definition 'message'.`
```c
void __sir_setoserror(int code, const char* msg, const char* func,
                                            ^
```
2. `sirerrors.c:67:45: note: Function '__sir_setoserror' argument 2 names different: declaration 'msg' definition 'message'.`
```c
void __sir_setoserror(int code, const char* message, const char* func,
                                            ^
```

**Comment by aremmell** [comment]
Fixed this one.
