### ISSUE TITLE
Useless check in sirdefaults.h:145:16 (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#25]
`sirdefaults.h:145:16: style: Operator '|' with one operand equal to zero is redundant. [badBitmaskCheck]`
```c
    = SIRO_ALL | SIRO_NOHOST;
               ^
```

**Comment by aremmell** [comment]
It's there for semantics; otherwise people won't grasp it–these options are exclusive, not inclusive, so setting one means "don't do this." without SIRO_ALL, it makes it seem like you're setting no options, but you're setting all of them.
