### ISSUE TITLE
Bad macro name in sirplatform.h:85 (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#27]
```c
# define assert(...) if (!(__VA_ARGS__)) { _sir_selflog(REDB("!!! would be asserting: "  #__VA_ARGS__ "")); }
```
* *Undefined behavior*: The '`assert`' macro name overrides a **reserved name** from the C standard.

**Comment by aremmell** [comment]
Only if you include `<assert.h>` right? I was looking for a way to avoid SIGABRT while trying to debug in llvm-db. Alternatively, I could see if there's a setting I'm missing, but as it stands, if I get any asserts while debugging, that's the end of my debugging session.

**Comment by johnsonjh** [comment]
We have a (kind of terrible) thing we do in the DPS8M sources, where we raise SIGUSR2 for explicit errors, and we have support for libbacktrace handling that; we generally don't use assert, — mostly because we *JUST* bumped our code base to C11.  But maybe something like that?

I'd actually love a macro like SIR_ABORT instead of ever calling abort() which would make it easy for us and others to use our existing crash handler.

**Comment by aremmell** [comment]
Okay, SIR_ABORT (or SIR_ASSERT) it is. I was just thinking about libbacktrace inclusion, but then I remembered I'm a library... do I really want to bring in more libraries?

**Comment by johnsonjh** [comment]
Example:
![IMG_7796](https://github.com/aremmell/libsir/assets/61629094/b99212ed-b701-4fc8-b910-e27e610cd96c)

We have some special DUMA (memory checker) support so it prints the line where an allocation happened too, but you get the idea.  It's obviously more interesting for real crashes.

We currently call it like:

![IMG_7797](https://github.com/aremmell/libsir/assets/61629094/3bfae9aa-8d0c-405f-8bb3-89ff13ef9940)

**Comment by johnsonjh** [comment]
> Okay, SIR_ABORT (or SIR_ASSERT) it is. 

That would be great, thanks.

> I was just thinking about libbacktrace inclusion, but then I remembered I'm a library... do I really want to bring in more libraries?

Probably not. Being a library, any `aborting()` is kind of rude, and you don't want to conflict (or work too hard not to conflict) with code others have in place already, as there is `libexecinfo`, glibc `backtrace()`, `libunwind`, Apple Libc supporting a `libunwind`-compatible API, etc.  If something really bad happens and going down can't help helped, providing a SIR_ASSERT/SIR_ABORT -  and defaulting it just `abort()` if the user doesn't configure it - suffices, I say.

(However, libbacktrace is pretty nice, and it works on AIX, Linux, macOS, Windows, and Free/Open/Net/DragonFly BSD, with minor caveats for each platform, but nothing too bad.)

**Comment by aremmell** [comment]
So, I went the hippie route. Essentially:

```c
#if defined(SIR_ASSERT_ENABLED)
# include <assert.h>
# define SIR_ASSERT(...) assert(__VA_ARGS__)
#else
# if defined(SIR_SELFLOG)
#  define SIR_ASSERT(...) \
      if (!(__VA_ARGS__)) { \
          _sir_selflog(LRED("!!! would be asserting: " #__VA_ARGS__ "")); \
      }
# else
#  define SIR_ASSERT(...)
# endif
#endif
```
I figure we'd better just not be the reason for an abort. That's our job. Agreed?
