### ISSUE TITLE
Useless asserts in sirfilecache.c (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#29]
`sirfilecache.c:434:`
```c
                assert(sfc->count > 0);
```
`sirfilecache.c:481:`
```c
            assert(sfc->count > 0);
```
* Useless assert: '`sfc->count > 0`' is **always** true.

**Comment by aremmell** [comment]
What if it was the only file?

**Comment by johnsonjh** [comment]
I'll see if it can give me more info.

**Comment by aremmell** [comment]
Looks like I already realized this was correct and removed it. Closing.
