### ISSUE TITLE
.lint.sh fails: clang: unknown warning option '-Winvalid-utf8'

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#291]
/usr/local/bin/ccache clang -MMD -std=c11 -Werror -Wassign-enum -Wbad-function-cast -Wconversion -DSIR_LINT=1 -Wdisabled-macro-expansion -Wdouble-promotion -Wextra-semi-stmt -Wformat=2 -Wformat-nonliteral -Winvalid-utf8 -Wmissing-prototypes -Wmissing-variable-declarations -Wno-sign-conversion -Wno-string-conversion -Wshift-overflow -Wstring-conversion -Wswitch-enum -Wall -Wextra -Wpedantic -Iinclude -fPIC -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -c -o build/obj/src/sir.o src/sir.c
error: unknown warning option '-Winvalid-utf8'; did you mean '-Winvalid-iboutlet'? [-Werror,-Wunknown-warning-option]

**Comment by johnsonjh** [comment]
Fixed in 94cd01aba50a390243e5d345ab1f27779174b3ec
