### ISSUE TITLE
Small but mighty CI improvements

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#300]
* Determine if this statement is true: "if you pass --with-extra-options=-Wdocumentation to Clang, it semantically checks your Doxygen markup with your code and generates documentation warnings." and if it's true, we should add that step so that the build will fail with invalid Doxygen markup.
* Make hunspell part of the 'style' step to catch typos and misspellings (if it's possible to do that without manual intervention. maybe it's possible to only scan between `/*` and `*/`?

**Comment by johnsonjh** [comment]
1. It's basic but I enabled it now - it'll be in #313 
2. No easy way with hunspell, but I'll look further.  We use scspell on other projects, but it's a rather manual process but works well once setup.
