### ISSUE TITLE
Coverage improvement opportunities

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#304]
After looking through the Coveralls report, I came up with this list of things we can do on the script side to bump up the coverage:

### sirtests

1. run with `--perf` (not getting coverage in file rolling routines). if already running with `--perf`, need to remove `.log` extension from file name
2. build and run with `SIR_NO_PLUGINS`

### sirtests++

1. run with `--only init-cleanup-raii`
2. run with invalid command line (e.g. `--badoption`)
3. run with `--wait`
4. figure out how to make one of the tests fail, then use `--only <that_test>` (i could add a hidden `--fail` option...)
5. figure out how to make one of the tests throw an exception, then use `--only <that_test>` (i could add a hidden `--throw` option ...)

**Comment by johnsonjh** [comment]
### sirtests

~1. run with `--perf` (not getting coverage in file rolling routines). if already running with `--perf`, need to remove `.log` extension from file name~
~2. build and run with `SIR_NO_PLUGINS`~

### sirtests++

~1. run with `--only init-cleanup-raii`~
~2. run with invalid command line (e.g. `--badoption`)~
~3. run with `--wait`~
4. figure out how to make one of the tests fail, then use `--only <that_test>` (i could add a hidden `--fail` option...)
5. figure out how to make one of the tests throw an exception, then use `--only <that_test>` (i could add a hidden `--throw` option ...)
