### ISSUE TITLE
Buffer underflow in tests.c:164-165 (branch: syslog)

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#36]
```c
    char toobig[SIR_MAXMESSAGE + 100] = {0};
    memset(toobig, 'a', SIR_MAXMESSAGE - 99);
```
* `memset` underflows buffer `toobig`.

**Comment by aremmell** [comment]
Well... I did that on purpose so it'd have a null term. I suppose i could explicitly add one after the fact to get rid of the warning. Thoughts?

**Comment by johnsonjh** [comment]
I wonder if it will complain about C11's [memset_](https://en.cppreference.com/w/c/string/byte/memset)?  As it's just a test, I don't mind iterating with a for loop either - speed isn't a concern.  I'm usually OK with something like that rather than make an exemption in non-critical code. I'll play with it in a bit.

**Comment by aremmell** [comment]
Here's the thing about `memset_s` (and all the `_s`es). I've *NEVER* seen `__STDC_LIB_EXT1__` defined, even though you can see that in sirplatform.h, the first thing I do is ask for it. Maybe you can help shed some light on that.

**Comment by johnsonjh** [comment]
I'll investigate
