### ISSUE TITLE
GitHub thinks libsir has no license

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#71]
I was looking at the insights page, and it recommended I add a license. Looks like that LICENSE file *has* to be there.

It can also be in LICENSES/MIT.txt (which I don't understand the purpose of), but we're going to need it in both spots if the new location is vital.

@johnsonjh comments?

**Comment by johnsonjh** [comment]
Yeah, REUSE and SPDX stuff requires it in the LICENSES directory.  We'll need to copy it to both places, if GitHub doesn't recognize it there (a symlink won't do sadly).

**Comment by aremmell** [comment]
No problem. I’m on it.

**Comment by aremmell** [comment]
Closed by 257ab9e
