### ISSUE TITLE
strncpy warning at sirhelpers.c:206

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#74]
Enabling GCC LTO and/or PGO can often uncover some additional warnings.

Tested on Linux (Fedora 38) with `gcc (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)` tested against https://github.com/johnsonjh/libsir-upstream-pr/commit/2e9b5a15dea95ebc77e0947ef5eb1b804721ac1e (#72).

`$ make clean; env CC="gcc" FORTIFY_FLAGS="-D_FORTIFY_SOURCE=3" CFLAGS="-Wformat -Wstringop-truncation -flto=auto -flto-partition=one" LDFLAGS="-flto=auto -flto-partition=one" make`

Results:

```sh
sirhelpers.c: In function ‘__sir_handleerr’:
sirhelpers.c:206:9: warning: ‘__builtin_strncpy’ specified bound 256 equals destination size [-Wstringop-truncation]
  206 |         strncpy(dest, src, count);
      |         ^
```

---

Wonder if you should just use a local strlcpy functions, since you're already using that elsewhere, for systems where it's missing...

**Comment by johnsonjh** [comment]
(like borrowing from [OpenBSD](https://github.com/openbsd/src/blob/master/lib/libc/string/strlcpy.c))

**Comment by aremmell** [comment]
Damn everyone who didn't implement _s versions of all of these.

**Comment by aremmell** [comment]
"Borrowing strlcpy" from BSD does sound like a fantastic idea, though. Good call.

**Comment by aremmell** [comment]
> (like borrowing from [OpenBSD](https://github.com/openbsd/src/blob/master/lib/libc/string/strlcpy.c))

Since you know all about this Unix stuff and licensing, do I have to attribute it if I just write what they wrote and not copy/paste it?

**Comment by johnsonjh** [comment]
Looks like only in the source file and we can do an SPDX tag on it - I'll make a PR for you to look at maybe?

**Comment by johnsonjh** [comment]
See #77
