### ISSUE TITLE
Data loss when writing <= SIR_FROLLSIZE bytes takes less than 1 second.

### ISSUE THREAD

**Issue by johnsonjh** [aremmell/libsir#9]
Loss of logged data easily happens by default:

```
        1000000 lines libsir(log file)...
        printf: 1000000 lines in 3.87sec (258353.5 lines/sec)
        libsir(stdout): 1000000 lines in 4.09sec (244663.9 lines/sec)
        libsir(log file): 1000000 lines in 4.99sec (200390.0 lines/sec)
        successfully deleted libsir-perf-23-06-22-181512 (5242913 bytes)...
        successfully deleted libsir-perf-23-06-22-181511 (5242913 bytes)...
        successfully deleted libsir-perf (465667 bytes)...
        successfully deleted libsir-perf-23-06-22-181510 (5242913 bytes)...
        successfully deleted libsir-perf-23-06-22-181513 (5242913 bytes)...
        deleted 5 log file(s)
```

So, OK, it *seems right*, but it isn't.  Data is being silently lost.

What happens if we set the roll size to 1MB?

```
        1000000 lines libsir(log file)...
        printf: 1000000 lines in 4.15sec (240687.9 lines/sec)
        libsir(stdout): 1000000 lines in 4.20sec (238195.6 lines/sec)
        libsir(log file): 1000000 lines in 4.93sec (202730.3 lines/sec)
        successfully deleted libsir-perf-23-06-22-182359 (1048599 bytes)...
        successfully deleted libsir-perf-23-06-22-182358 (1048599 bytes)...
        successfully deleted libsir-perf-23-06-22-182401 (1048599 bytes)...
        successfully deleted libsir-perf (468847 bytes)...
        successfully deleted libsir-perf-23-06-22-182400 (1048599 bytes)...
        deleted 5 log file(s)
```

Ouch, that's a problem, lots of data lost. We're losing all the logged data if we write more than whatever the roll size is per second.

I have my own fork in which I use a sequence number to avoid this issue:

```
        deleting logperf (size: 883990)...
        deleting logperf-2023-06-22-221218-000 (size: 1048590)...
        deleting logperf-2023-06-22-221220-001 (size: 1048590)...
        deleting logperf-2023-06-22-221221-002 (size: 1048590)...
        deleting logperf-2023-06-22-221222-003 (size: 1048590)...
        deleting logperf-2023-06-22-221223-004 (size: 1048590)...
        deleting logperf-2023-06-22-221225-005 (size: 1048590)...
        deleting logperf-2023-06-22-221226-006 (size: 1048590)...
        deleting logperf-2023-06-22-221227-007 (size: 1048590)...
        deleting logperf-2023-06-22-221228-008 (size: 1048590)...
        deleting logperf-2023-06-22-221229-009 (size: 1048590)...
        deleting logperf-2023-06-22-221231-010 (size: 1048590)...
        deleting logperf-2023-06-22-221232-011 (size: 1048590)...
        deleting logperf-2023-06-22-221233-012 (size: 1048590)...
        deleting logperf-2023-06-22-221234-013 (size: 1048590)...
        deleting logperf-2023-06-22-221236-014 (size: 1048590)...
        deleting logperf-2023-06-22-221237-015 (size: 1048590)...
        deleting logperf-2023-06-22-221238-016 (size: 1048590)...
        deleting logperf-2023-06-22-221240-017 (size: 1048590)...
        deleting logperf-2023-06-22-221241-018 (size: 1048590)...
        deleting logperf-2023-06-22-221242-019 (size: 1048590)...
        deleting logperf-2023-06-22-221243-020 (size: 1048590)...
        deleting logperf-2023-06-22-221245-021 (size: 1048590)...
        deleting logperf-2023-06-22-221246-022 (size: 1048590)...
        deleted 24 log file(s)
```

No data lost there. 

I propose that a sequence number be used, and if the filename exists instead of being re-used, increment the sequence number.  Works for me, but other solutions are possible too.

I have my own fork of this tool, but since I see you have it here and you are actively maintaining it, I should probably re-sync to this code, and see what I can upstream of my own changes!  This was the first thing that struck me as a showstopper that I needed to fix.

Ideally, also do some additional safety checks before overwriting (or deleting!) any log files, to avoid other potential issues; I'll probably open another ticket for that.

**Comment by johnsonjh** [comment]
@aremmell ?

**Comment by aremmell** [comment]
Sorry, I didn't see the first notification. Thanks for spying that; I've never hit it, apparently, since I've never changed the roll size. If I think back to when I wrote that, I thought it checked if it needed to roll the log every time it wrote a line, but maybe I'm misremembering.

Anyway, when did you fork? I've been dev'ing on the 'syslog' branch for a bit now, and that's got some perf increases, support for syslog (and os_log on macos), and I'm about to start on 256-color and RGB color support. The test rig has command-line options now too, like --only if you just want to run a certain set of tests. A few bug fixes as well.

I can let you know when I merge back into main. It's kind of shaky right now if I'm honest. I changed a ton of code trying to optimize for perf, which will just make the bug you found worse haha.

**Comment by johnsonjh** [comment]
Oh, way back in 2018 or 2019.  I've not actually used it for the intended purpose yet, so no foul.

It's hard to see what I've done with ti because I completely reformatted all the code!  But I'll figure it out.

One thing I did was make sure it compiled without any warnings on AIX, Solaris, illumos, Haiku, OpenBSD, NetBSD, FreeBSD, and Linux with bionic and musl.  There were some issues there.  Also, I had it passing clang-analzyer, cppcheck, and PVS-Studio.  Most of it was the obvious stuff and I'll contribute that back - mostly making sure to use the right strerror_r implementation and the differing magic for things like getting the thread IDs.  This was all code you refactored here lately, so it should be easy enough.

**Comment by johnsonjh** [comment]
It's kind of but not exactly what's in my github - best just ignore that and I'll send some PR's over based on your current code.

**Comment by johnsonjh** [comment]
Oh, I'm planning to use this, or something derived from it, as part of [DPS8M](https://dps8m.gitlab.io/) so it means it has to support, at a minimum, [all the operating systems and compilers we officially support.](https://dps8m.gitlab.io/dps8m/Overview/#simulator-overview)

**Comment by johnsonjh** [comment]
Back on topic - another fix might be adding milliseconds to the timestamp.

**Comment by aremmell** [comment]
> It's hard to see what I've done with it because I completely reformatted all the code!

I've got it on my TODO to use clang-format because it's driving me insane how many different styles I've had over the last 5 years and mixed them all together. I'm glad to hear you did that though.

> One thing I did was make sure it compiled without any warnings on AIX, Solaris, illumos, Haiku, OpenBSD, NetBSD, FreeBSD, and Linux with bionic and musl. I also build with multiple compilers: IBM XL C/C++ 16 & 17, PGCC/NVC, Oracle Studio, etc. There were some issues there. Also, I had it passing clang-analzyer, cppcheck, and PVS-Studio.

This is great to hear. I only recently got FreeBSD and a bunch of Linux distros on the list of platforms I test on (+Windows). I have not tried any compilers other than Clang/GCC/MSVC (cl).

I am very interested to see what those tools had to say (I think I have clang-analyzer enabled in my VS Code project). I did recently refactor the error string formatting routine which checks all the preconditions for using XSI strerror_r etc.

> Oh, I'm planning to use this, or something derived from it, as part of [DPS8M](https://dps8m.gitlab.io/) so it means it has to support, at a minimum, [all the operating systems and compilers we officially support.](https://dps8m.gitlab.io/dps8m/Overview/#simulator-overview)

That is amazing. I'm glad it will be put to good use–I just hope you'll wait till I merge the syslog branch back in and then cherry-pick the fixes and perf gains.

Maybe before I do that, I'll finalize a draft plugin architecture and implement the loader / abstraction interface, if you can see that being something useful for you in the future. I was thinking it would be cool to have plugins that could, for example, post to a REST API endpoint in case of an emergency-level event–the user could get a push notification or an email, etc.

> Back on topic - another fix might be adding milliseconds to the timestamp.

That's easy enough. I will give it a go. That being said, whatever system you repro'd that bug on is 100% faster than this 8-core 3.2GHz Xeon W iMac Pro I'm using. I have never seen sub 8-second or more than about 100k lines/s in the perf test.

Also of note, lately I have added `-Wall` and `-DFORTIFY_SOURCE=2` to the makefile. I fixed a lot of warnings with Visual Studio's highest warning level as well.

**Comment by aremmell** [comment]
What version of `clang-analzyer` do you use? The newest one I can find is from 2016... (279)

**Comment by johnsonjh** [comment]
The analyzer and it's more configurable counterpart (tidy) is now included with current Clang versions:

`env CC=clang scan-build gmake`

12 bugs found in current master:

![IMG_7794](https://github.com/aremmell/libsir/assets/61629094/a3d50f7c-e7a0-4bf1-b686-ecd876b6898c)

I will attach the full interactive report in a bit (when I am back at my desktop), but here is the summary:

![IMG_7795](https://github.com/aremmell/libsir/assets/61629094/d7fbfe0c-74d1-45d4-b8f2-8148067a57fa)

**Comment by johnsonjh** [comment]
Here is a short cppcheck run - it can be integrated for better testing, but these are ones I'd need to fix:

```

jhj@brshpc0 ~/src/libsir-upstream $ cat cppcheck-1.txt
sirhelpers.h:119:12: style: Redundant condition: p. '!p || (p && !*p)' is equivalent to '!p || !*p' [redundantCondition]
    if (!p || (p && !*p))
           ^

sirerrors.c:71:50: style: inconclusive: Function '__sir_setoserror' argument 2 names different: declaration 'msg' definition 'message'. [funcArgNamesDifferent]
void __sir_setoserror(int code, const sirchar_t* message, const sirchar_t* func,
                                                 ^
sirerrors.h:108:50: note: Function '__sir_setoserror' argument 2 names different: declaration 'msg' definition 'message'.
void __sir_setoserror(int code, const sirchar_t* msg, const sirchar_t* func,
                                                 ^
sirerrors.c:71:50: note: Function '__sir_setoserror' argument 2 names different: declaration 'msg' definition 'message'.
void __sir_setoserror(int code, const sirchar_t* message, const sirchar_t* func,
                                                 ^

sirerrors.c:109:15: style: The comparison '0 == finderr' is always true. [knownConditionTrueFalse]
        if (0 == finderr && _sir_validstrnofail(message)) {
              ^
sirerrors.c:85:23: note: 'finderr' is assigned value '0' here.
        int finderr = 0;
                      ^
sirerrors.c:109:15: note: The comparison '0 == finderr' is always true.
        if (0 == finderr && _sir_validstrnofail(message)) {
              ^

sirhelpers.c:210:21: portability: Assigning a pointer to an integer is not portable. [AssignmentAddressToInteger]
        errno_t ret = localtime_s(buf, timer);
                    ^

tests/tests.c:643:9: warning: %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'. [invalidPrintfArgType_sint]
        printf("\tdeleted %d log file(s)\n", deleted);
        ^

tests/tests.c:497:22: warning: Redundant assignment of 'err' to itself. [selfAssignment]
        uint16_t err = err = sir_geterror(message);
                     ^
```

**Comment by aremmell** [comment]
Thanks, that’s super useful. I’ll fix those today.

Ryan M. Lederman
"I would rather wake up in the middle of nowhere than in any city on Earth." — Steve McQueen
208-631-5654
***@***.***

**Comment by johnsonjh** [comment]
All of these seem very familiar so I know I've fixed them in my local code.

If you want PR's should I give you them against master or against syslog branch?

**Comment by aremmell** [comment]
Against the syslog branch would be perfect. It’s diverged quite a bit from master though so you’d have to re-run that.

**Comment by johnsonjh** [comment]
Sounds good.  I'll make separate issues for these.

**Comment by johnsonjh** [comment]
Back on track and on-topic with this issue - still thinking what the best way to solve this would be, but I have to get more familiar with the latest code.

**Comment by aremmell** [comment]
Let me show you what I just worked on for the last few hours. Also, I invited you to be a collaborator–you should have an email or notification.

Committed just now; pull syslog again and look at `sirfilecache.c::_sirfile_roll`

**Comment by johnsonjh** [comment]
I like your hybrid solution, seems to work well.  I want to think of ways to break it, but, looking good so far:

![IMG_7798](https://github.com/aremmell/libsir/assets/61629094/bb1d63b0-06c7-467a-848f-10e3922b9690)

**Comment by aremmell** [comment]
Yeah, I first implemented the milliseconds plan, but it felt hacky. It didn't have a retry like this one... at least this way, it'll try real hard to find a new path.

I realized this morning that I've never tested with absolute paths, so that's something that needs to happen ASAP. Need to ensure that it rolls those properly (i.e. takes into account the path to the old log and doesn't just stick it in $CWD.

**Comment by johnsonjh** [comment]
Looks good.  A minor concern is that sorting order might be changed - so it might make more sense to have a format by default of something like YY-MM-DD-SSSS-TTTTTT, where S is the sequence number, starting at 0000.

**Comment by johnsonjh** [comment]
![IMG_7799](https://github.com/aremmell/libsir/assets/61629094/29e9bf1e-bea0-4c91-b625-5cd11801042d)

1 MiB log case looks good.

Writing 10 MiB logs seems a bit faster.

![IMG_7800](https://github.com/aremmell/libsir/assets/61629094/cb573954-7435-42ec-a619-0abe26f72138)

**Comment by johnsonjh** [comment]
> That being said, whatever system you repro'd that bug on is 100% faster than this 8-core 3.2GHz Xeon W iMac Pro I'm using. I have never seen sub 8-second or more than about 100k lines/s in the perf test.

IBM POWER, RAID10 SSD.  I have an Intel system here with faster I/O as well, I think.

> Also of note, lately I have added -Wall and -DFORTIFY_SOURCE=2 to the makefile. I fixed a lot of warnings with Visual Studio's highest warning level as well.

They recently introduced a Level 3 to FORTIFY, but it's not widely supported yet.  Also, I usually fix all the warnings with `-Wall -Wextra -Wpedantic -Wformat=2

**Comment by johnsonjh** [comment]
@aremmell 

I think I'm happy with this as it is now in syslog branch - if there are any other problems I can open a new issue.  Want to close this one?

**Comment by aremmell** [comment]
Closing.
