### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#91]
- [x] Design plugin interface
- [x] Create dummy plugin
  - [x] Create purposefully misbehaving dummy plugins to test failure paths 
- [x] Implement loader
- [x] Add to dispatch targets
- [x] Document
  - [x] Exported functions
  - [x] plugins/sample/plugin_sample.h
  - [x] Add a markdown page to docs

**Comment by aremmell** [comment]
I think I'm gonna do this, then call it good for a while afterward (unless we start getting traction).

@johnsonjh what do you think of this so far?

```c
# define SIR_PLUGIN_V1 1
# define SIR_PLUGIN_VCURRENT SIR_PLUGIN_V1

/* The libsir-to-plugin query data structure. */
typedef struct {
    uint8_t iface_ver; /**< Plugin interface version (set to SIR_PLUGIN_V1). */
    uint8_t maj_ver;   /**< Major version number. */
    uint8_t min_ver;   /**< Minor version number. */
    uint8_t bld_ver;   /**< Build/patch version number. */
    char* author;      /**< Plugin author information. */
    char* description; /**< Plugin description. */
} sir_plugin_info;

/**
 * @brief Called by libsir after the plugin library object is loaded, but before
 * any other functions are probed or called.
 *
 * The plugin must fill out the informtaion in the `info` structure in a way
 * satisfactory to libsir, or it will immediately be unloaded.
 *
 * - `iface_ver` should be set to `SIR_PLUGIN_CURRENT_VER`; if the interface
 * version does not match libsir's expectation, the plugin will be unloaded.
 * - `char*` members must be malloc'd by the plugin, and will be freed by libsir.
 *
 * @param   info Pointer to a ::sir_plugin_info structure to be initialized by
 * the plugin.
 * @returns bool `true` if the `info` structure was successfully initialized,
 * `false` otherwise.
 */
bool sir_plugin_loaded(sir_plugin_info* info);
```

**Comment by johnsonjh** [comment]
Fix "informtaion" typo and it's a good start :) /s

I think it's important that plug-ins be optional (since it will depend, I assume, on functionality like dlopen/dlsym/dlfcn or LoadLibrary, no?). And also having a way to have these extensions/plugins static compiled and linked as well.

**Comment by johnsonjh** [comment]
I can think of two uses cases - plugins that define new output methods, like, say, a syslog logging plugin that uses RELP.  

The second would be plugins that extend the formatting functionality.  Like, allowing a new format string type - say, %b for printing in binary (0101001001) - that's actually something I do want.  Or as another example, giving someone the ability to make a plug-in that prints EBCDIC input as ASCII output, or converts KOI8 inputs to print UTF-8 outputs.

The first class will probably be easier than the second class.  

Don't waste much time on it, just a wishlist on my part.

**Comment by aremmell** [comment]
Yeah, definitely will be able to be compiled out like system logger functionality. If you have any bright ideas about how to enforce some kind of PGP signature on the libraries without adding any dependencies that we'll have problems with, I'm all eyes.

I was also thinking we could just have an 'apt' style package server where these would be stored, and only if you got it from there and verified the sha-256 would you be willing to send your log messages there. Presumably, people will only load the plugin they wrote, unless something changes and suddenly people care about writing C/C++ and want a cool way to output information. *shrug* I guess they all roll their own.

The extension for formatting would be great. On that topic, I was also thinking what I want to do is trash the way it works right now (compile time organization of formatted output) and let the user set their own format string like `%(level) %(time) ^%(pid)^ ~ %(message)`

**Comment by aremmell** [comment]
Okay, a little more brain vomit:

```cpp
# define SIR_PLUGIN_V1 1
# define SIR_PLUGIN_VCURRENT SIR_PLUGIN_V1

/* The libsir-to-plugin query data structure. */
typedef struct {
    uint8_t iface_ver; /**< Plugin interface version. */
    uint8_t maj_ver;   /**< Major version number. */
    uint8_t min_ver;   /**< Minor version number. */
    uint8_t bld_ver;   /**< Build/patch version number. */
    sir_levels levels; /**< Level registration bitmask. */
    sir_options opts;  /**< Formatting options bitmask. */
    char* author;      /**< Plugin author information. */
    char* description; /**< Plugin description. */
    uint64_t caps;     /**< Future-proof plugin capabilities bitmask. */
} sir_plugin_info;

/**
 * @brief Called by libsir after the plugin library object is loaded, but before
 * any other functions are probed or called.
 *
 * The plugin must fill out the information in the `info` structure in a way
 * satisfactory to libsir, or it will immediately be unloaded.
 *
 * - `iface_ver` should be set to `SIR_PLUGIN_CURRENT_VER`; if the interface
 * version does not match libsir's expectation, the plugin will be unloaded.
 * - `char*` members must be malloc'd by the plugin, and will be freed by libsir.
 *
 * @param   info Pointer to a ::sir_plugin_info structure to be initialized by
 * the plugin.
 * @returns bool `true` if the `info` structure was successfully initialized,
 * `false` otherwise.
 */
bool sir_plugin_query(sir_plugin_info* info);

// loaded, passed the checks on data from `sir_plugin_query`. Plugin should
// initialize its internal state.
bool sir_plugin_init(void);

// handler for log message writes. must complete *very* quickly, or if unable to
// guarantee quick completion (i.e. network operation involved), must be async.
bool sir_plugin_write(sir_level level, const char* message);

// the plugin is about to be unloaded, and should stop any ongoing operations
// and clean up allocated resources.
bool sir_plugin_shutdown(void);
```

**Comment by aremmell** [comment]
> I can think of two uses cases - plugins that define new output methods, like, say, a syslog logging plugin that uses RELP.

I confess, I don't know what RELP is.

**Comment by aremmell** [comment]
> must complete *very* quickly, or if unable to guarantee quick completion (i.e. network operation involved), must be async

This just made me realize there is a bug in libsir–if a log file is on a network drive, and it gets unmounted or the server reboots, etc. we could stall on write and therefore hang up the thread that called into us... I think we're going to need a thread pool for writes to things like files, and especially plugins.

**Comment by johnsonjh** [comment]
There is no good way to sign logs securely and easily.  There are some good solutions tho: see https://rainer.gerhards.net/2018/06/rsyslogs-first-signature-provider-why.html for example, with implementation documented [here](https://www.rsyslog.com/doc/master/configuration/modules/sigprov_gt.html).

IMO that is something so hard to get right, best to not try to add it as part of the base.  The way GuardTime works is really the best and AFAIK they are the only people who have a peer reviewed solution that works *and* allows you to share only a part of the log and have that part be verifiable.  But as it explains this solution can't run completely on one system.  It needs some parts to be external.

They've moved to https://guardtime.com/ since the original blog entry was written.

Systemd has "forward secure sealing" but it's way less awesome than GuardTime, and it works on one machine.  See https://louwrentius.com/systemd-forward-secure-sealing-of-system-logs-makes-little-sense.html for why it sucks - it's been made better since this was written but I do still think you should just ship the logging out to systemd if you want that ...

**Comment by johnsonjh** [comment]
RELP is https://en.wikipedia.org/wiki/Reliable_Event_Logging_Protocol

**Comment by aremmell** [comment]
> RELP is https://en.wikipedia.org/wiki/Reliable_Event_Logging_Protocol
> 
> Edit: It's essentially _the_ standard for shipping logs around at banks. The receiver acknowledges the log being received and committed, so if the logging host goes down, the sender can buffer until it comes back, so no entries get lost.

What if the sender goes down while the logging host goes down? I guess it probably keeps a local cache that has atomic transactions.

I assumed this was built in to syslog. That's why they say "you know what assume means?" It means make an 'ass' out of 'u' and 'me'.

**Comment by johnsonjh** [comment]
> Yeah, definitely will be able to be compiled out like system logger functionality. If you have any bright ideas about how to enforce some kind of PGP signature on the libraries without adding any dependencies that we'll have problems with, I'm all eyes.
> 
> I was also thinking we could just have an 'apt' style package server where these would be stored, and only if you got it from there and verified the sha-256 would you be willing to send your log messages there. Presumably, people will only load the plugin they wrote, unless something changes and suddenly people care about writing C/C++ and want a cool way to output information. _shrug_ I guess they all roll their own.
> 
> The extension for formatting would be great. On that topic, I was also thinking what I want to do is trash the way it works right now (compile time organization of formatted output) and let the user set their own format string like `%(level) %(time) ^%(pid)^ ~ %(message)`

Let's not break too much now :) I really want to start using it soon!

**Comment by aremmell** [comment]
Let me add some color mode switching to the thread-race test, to make sure that stuff jives, then we should be GTG.

PR incoming in 15 mins.

**Comment by johnsonjh** [comment]
> What if the sender goes down while the logging host goes down? I guess it probably keeps a local cache that has atomic transactions.

The normal way that it's handled IRL is that logs are sent to at least two (and usually to three) different hosts. The logged data can be de-duplicated and this also gives extra assurance of integrity.

**Comment by johnsonjh** [comment]
I'll get AIX landed too - that should be mostly self-contained.

**Comment by aremmell** [comment]
> I'll get AIX landed too - that should be mostly self-contained.

K. There is one more thing I should do... add `--leave-logs` to the test rig. This would prevent it from deleting the logs it generates so a human can read them and make sure they look right.

This has been neglected way too long, and if I remember correctly, years ago I saw a bug where it would randomly print the session begin header (in the same thread, without skipping a beat).

Maybe that's still there and we can crush it, and maybe there's bugs we don't even know about.

**Comment by aremmell** [comment]
Already found a bug. Tests for the win.

**Comment by aremmell** [comment]
There isn't a very good way to resolve this. Here's the issue:

- 4 threads are battling for control of the color mode, options, etc.
- We can prevent multiple thread for racing on the actual mode setting, but they can try to set foreground and background colors that are now invalid for the mode set by another thread, which will fail.

We can:

- Mutex the test
- Ignore failures involving invalid colors

**Comment by aremmell** [comment]
Yeah, there is nothing you can do about this race–the colors may be mutex guarded but that doesn't stop one thread from waiting to set colors that will be invalid when the mutex is released. I'm just going to take it out of the test; nobody's going to be calling `sir_setcolormode` over and over from different threads. if they do, f them.

**Comment by aremmell** [comment]
@johnsonjh can you please make the Makefile delete `*.log` *and* `logs/*`? Right now it just deletes `*.log`

**Comment by johnsonjh** [comment]
@aremmell Done in new PR.  It does the whole directory if that's OK.  I'll add to .gitignore too

**Comment by johnsonjh** [comment]
@aremmell will address Makefiles later ...

**Comment by aremmell** [comment]
This is done. Still need to implement a thread pool so that dispatches are virtually guaranteed to never block.
