### ISSUE TITLE
Conditional logging

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#94]
Write wrapper functions around `sir_debug` and friends that essentially are:

```cpp
bool sir_debug_if(bool cond, const char* format, ...) {
    return cond ? sir_debug(format, va_args) : true;
}
```

**Comment by aremmell** [comment]
@johnsonjh what do you think about this feature? Unnecessary or cool?

**Comment by johnsonjh** [comment]
Don't think it's really needed myself

**Comment by aremmell** [comment]
`if ()` is good enough on its own. Closing.
